PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.com/ns#>

SELECT ?s1 ?d1s1 ?d2s1  
WHERE { 
	OPTIONAL { 
		?s1 ex:d1 ?d1s1 .
		?s1 ex:d2 ?d2s1 .
		?s2 ex:d1 ?d1s2 .
		?s2 ex:d2 ?d2s2 .
	FILTER ( ?d2s2 >= ?d2s1  &&  ?d1s2 >= ?d1s1 && ( ?d2s2 > ?d2s1 || ?d1s2 > ?d1s1  ))
	}
	FILTER (!BOUND(?s2))
}