PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mpv: <http://mappingpedia.linkeddata.es/vocabulary#>

SELECT ?a1 ?gpa1 ?r1 
WHERE { 
	?a1 mpv:hasSport ?s1 .
	?a1 mpv:gpa ?gpa1 .
	?s1 mpv:ranking ?r1
	OPTIONAL { 
		?a1 mpv:hasSport ?s1 .
		?a1 mpv:gpa ?gpa1 .
		?s1 mpv:ranking ?r1.
		?a2 mpv:gpa ?gpa2 .
		?a2 mpv:hasSport ?s2 .
		?s2 mpv:ranking ?r2 .
		FILTER ( ((?gpa2 >= ?gpa1) && ( ?r2 >= ?r1 )) && ( ( ?gpa2 > ?gpa1 ) || ( ?r2 > ?r1 ) ) )
	}
	FILTER (!BOUND(?a2))
}